### ISSUE TITLE
Goroutines example needs a time.Sleep()

### ISSUE THREAD

**Issue by ysagal** [mmcgrana/gobyexample#103]
Without time.Sleep(), the execution of goroutines isn't interleaved. It might also be worth noting in this early example why a Scanln is required—main() won't wait for goroutines to finish and since they're returned immediately getting to the end of main() ends the execution.

```
➜  goroutines git:(master) go run goroutines.go
direct : 0
direct : 1
direct : 2
goroutine : 0
goroutine : 1
goroutine : 2
going

done
```

**Comment by mmcgrana** [comment]
The exact interleaving that's observed is implementation / platform dependent. There certainly _could_ be some interleaving with the current code, but it wont always happen. My goal with this section is mostly to demonstrate the syntax of Goroutines, so I'm not going to add more complexity to this example.
