### ISSUE TITLE
Examples of printing to various streams

### ISSUE THREAD

**Issue by simar7** [mmcgrana/gobyexample#117]
Thanks for your work so far! This has really helped me pick up the language at a rapid pace.

Just a small request: Would you think it'll be a nice feature to add the various ways of redirecting output to various output streams available? (e.g. fmt package, maybe others)

**Comment by mmcgrana** [comment]
Sorry, as I just mentioned in another issue you had opened I won't be adding any more sections to the site. Sorry and I hope you've been able to read about printing to other output streams elsewhere |:
