### ISSUE TITLE
Examples of commenting in Go

### ISSUE THREAD

**Issue by simar7** [mmcgrana/gobyexample#119]
Something I ran into while using the language. We could add a page that describes people how to comment in the language. Keeping this as a placeholder for myself to add a diff to.

**Comment by mmcgrana** [comment]
Sorry I'm only responding to this issue now /:

I'm actually not planning to add any more sections to Go by Example. A section son comments is a very reasonable idea but due to personal bandwidth limitations I need to not increase the scope of the site at this point. Sorry!
