### ISSUE TITLE
worker pools example program can deadlock

### ISSUE THREAD

**Issue by kostya-sh** [mmcgrana/gobyexample#125]
The example relies on the fact that `jobs` and `results` channel buffers are big enough. If the code is changed to use smaller buffers for these channels:

```
jobs := make(chan int, 2)
results := make(chan int, 2)
```

then example program will deadlock: http://play.golang.org/p/whGg0n8qgT

Also in practice number of jobs is variable and it is hard to find the right size for the channels buffer that will work in all cases. This should at least be explained on the example page.

**Comment by mmcgrana** [comment]
Thanks for noting this. I agree that such a setup can cause a deadlock as you indicate. I am not going to include a discussion of deadlocks in the example though, for the sake of brevity.

**Comment by kostya-sh** [comment]
I beleive the best fix for this issues would be rewriting the example in such a way that it cannot deadlock. In its current form the code from the example most likely won't work in real applications where number of jobs and their duration is not known in advance. Additionally it shows some questionable programming practices (why channel size is hardcoded to 100 without any explanation?).
