### ISSUE TITLE
range: new example

### ISSUE THREAD

**Issue by poopoothegorilla** [mmcgrana/gobyexample#127]
I added a new example to the range examples.
I noticed that when I ran the rebuild command it replaced `<em>` with `_`... is this correct?

also how do people feel about this example?

https://github.com/mmcgrana/gobyexample/pull/126

**Comment by mmcgrana** [comment]
Thanks for the suggestion! I've cherry-picked the two changes you made to source files and run the rebuild on my side to reflect the change in `/public`.

Honestly I'm not sure what the deal is `<em>` vs `_` and don't have time to chase it down right now |: it's not a big deal though, happy to run these rebuilds on my side.
