### ISSUE TITLE
Comments with different languages

### ISSUE THREAD

**Issue by pavlik** [mmcgrana/gobyexample#135]
What about ability to add comments in different languages?
for example:
// en: This is english comment
// ru: This is Russian comment
// ch: This is China comment

And at compile time specify the flag for a compiled language.
This will give the opportunity for changed and new examples to quickly add and edit comments for different languages.

For now I fork your repo to translate for Russian language. And if happened changes in your repo I need to watch it & modify my files.
What do you think about it?

Pavel - author of Russian version of your perfect project http://gobyexample.ru/

**Comment by squanto** [comment]
👍

**Comment by robbert229** [comment]
This makes sense. +1

**Comment by robbert229** [comment]
How do you plan on handling comments that stretch across multiple line. A ch: every single line? Or is it a Chinese comment until anow English comment starts?

**Comment by mmcgrana** [comment]
Hi, thanks for the suggestion, but unfortunately I don't plan to implement this feature. I only have bandwidth to manage the English version and while I would like to make things easier for translators where possible, I'm not willing to make the English repo more complex to accomplish it. Sorry!!

BTW if you'd like to link to the Russian translation from the Readme lmk.
