### ISSUE TITLE
Consider more interactive code snippets via Sourcegraph?

### ISSUE THREAD

**Issue by beyang** [mmcgrana/gobyexample#142]
Hey Mark, thanks for making this excellent resource. It's a great learning tool for new members of my team who are picking up Go for the first time.

Would you accept a pull request to make the snippets on Go by Example more interactive? For example, [this snippet](https://gobyexample.com/stateful-goroutines) could function [like this](https://sourcegraph.com/github.com/mmcgrana/gobyexample@c9672f5fd20a64871f7c202d8194e512a0679248/-/blob/examples/stateful-goroutines/stateful-goroutines.go) to help newbies easily jump-to-def and explore the code. Or alternatively, have a small link like you do to code on the Go playground for each snippet.

In full transparency, I'm one of the creators of Sourcegraph, so I'm a little biased, but I think visitors would find interactive snippets really cool and useful.

**Comment by mmcgrana** [comment]
Thanks for the suggestion. Dan from Sourcegraph had actually reached about this directly over email previously. I'm not interested at this time but good luck with Sourcegraph which looks neat!
