### ISSUE TITLE
Have a «Previous example» link

### ISSUE THREAD

**Issue by rndstr** [mmcgrana/gobyexample#144]
From a Google search I landed on https://gobyexample.com/stateful-goroutines which says 

>  In the previous example we used […]

But I can't find any way to go to that previous example.

The generator should also include a «Previous example: Foo» link the same way it has a «Next example: Sorting» link.

**Comment by mmcgrana** [comment]
Thank you for flagging.

I've added some inline links where we explicitly mention the "previous example", including on /stateful-goroutines.

I am not planning on changing the overall navigation structure of the site at this time. I understand that it can sometimes be helpful to have a previous link, but I am trying to keep the structure as minimal as possible. This request comes in occasionally, so I've added a note about it in CONTRIBUTING.md.
