### ISSUE TITLE
mutexes is not work now

### ISSUE THREAD

**Issue by thanhngvpt** [mmcgrana/gobyexample#149]
Hi guy.
This https://gobyexample.com/mutexes is not work on both go play and local. it talk process take long.

**Comment by mmcgrana** [comment]
Huh, that's weird. It worked for me fine locally but the playground doesn't like it. I think it has something to do with hammering on `runtime.Gosched`. I've just removed the calls to this in favor of `Sleep`s which seems to make things work on the playground again.
