### ISSUE TITLE
tickers example is leaking a goroutine

### ISSUE THREAD

**Issue by dividinglimits** [mmcgrana/gobyexample#152]
See https://rakyll.org/leakingctx/

**Comment by kav2k** [comment]
I think you meant the "Rate Limiting" example. But, yes, came here to say the same.

    go func() {
        for t := range time.Tick(time.Millisecond * 200) {
            burstyLimiter <- t
        }
    }()

This is going to hang on channel write when the caller stops reading from `burstyLimiter`.

**Comment by mmcgrana** [comment]
I'm aware of this but don't want to complicate these examples to handle these "leak", especially since the programs by design exit very quickly (:

**Comment by amarnus** [comment]
I hope that the decision to close this can be revisited.

The current code on the site can easily cause a memory leak when used as-is from within a larger program that is a long-running service, say. [The fix](https://github.com/mmcgrana/gobyexample/pull/206/files) is actually not that complicated and is similar to the [Timers example](https://golang.org/pkg/time/#Ticker) in the documentation.

**Comment by dbenders** [comment]
I strongly advise to change this. A lot of people use this example as a coding tip, and producing a goroutine leak is quite serious and very difficult to track.

**Comment by eliben** [comment]
@dbenders This has been superseded by the discussion in #206

**Comment by blixt** [comment]
I just found leaks in our production code leading back to this example (it had been copied by someone who wanted to run code regularly and Google led them here). While the examples are quickly running, this code does spread into real code and sometimes makes its way past code reviews.
