### ISSUE TITLE
Unable to run code in Go Playground

### ISSUE THREAD

**Issue by RXue92** [mmcgrana/gobyexample#157]
Hi,

I really enjoy learning Go with your examples but when I click the top right corner of the code block to redirect to Go Playground to run the code it shows

```
<h1>Unavailable For Legal Reasons</h1><p>If you believe this is in error, please <a href="https://golang.org/issue">file an issue</a>.</p>
```
This happens everytime I try to run the code ([for example](https://gobyexample.com/closures)). I also tried to do the same thing with some examples in the [Russian version](https://gobyexample.ru/) and I got same messages.
I'm not sure whether you can reproduce the same issue but I can open play.golang.org and run code in there.

**Comment by alexbilbie** [comment]
If you are connecting to golang.org from China then the website is blocked due to the Chinese government blocking Google's IP ranges - see https://github.com/golang/go/issues/8870#issue-51288808

**Comment by RXue92** [comment]
@alexbilbie Thanks for your reply. I have changed my host file so that I can access golang.org or go playground freely, but I cannot access any pages intended to share code written in go playground, like https://play.golang.org/p/gQtEWkhWyp
Although I don't know why this problem happens, I'm pretty sure that it's not relented to this project so I'm closing this issue.
