### ISSUE TITLE
A Triditional Chinese version of Go by Example

### ISSUE THREAD

**Issue by CasperHK** [mmcgrana/gobyexample#161]
Hello. I am working on a triditional chinese version of Go by Example for Hong Kong people and Taiwanese. Here is the link to the GitBook: https://www.gitbook.com/book/casperli/go-by-example/details

**Comment by mmcgrana** [comment]
Is https://casperli.gitbooks.io/go-by-example-hk/content/ the appropriate place to link to? (Seems like what a reader would be most directly interested in?)

**Comment by mmcgrana** [comment]
And thanks for the translation! (:

**Comment by mmcgrana** [comment]
Hi. As far as I can tell this isn't finished at this time. But if it is or if it becomes finished at some point, do let me know along with the exact URL to link to.
