### ISSUE TITLE
File read into a []byte slice issue...

### ISSUE THREAD

**Issue by fohristiwhirl** [mmcgrana/gobyexample#165]
https://gobyexample.com/reading-files

"Read some bytes from the beginning of the file. Allow up to 5 to be read but also note how many actually were read."

    b1 := make([]byte, 5)
    n1, err := f.Read(b1)
    check(err)
    fmt.Printf("%d bytes: %s\n", n1, string(b1))

Thing is, if less than 5 bytes are read, the remainder of the []byte slice will still contain NULL (\0) characters, and these will become part of string(b1) and be printed (perhaps invisibly, but still).

On the other hand, say the file is 6 bytes long. If the slice is reused later to read more bytes, the 2nd read will change the first byte only, and the rest of the slice will retain its contents from the first read.

If one wants to print this correctly, one should do this I guess:

    fmt.Printf("%d bytes: %s\n", n1, string(b1[0:n1]))

**Comment by eliben** [comment]
This seems reasonable. Would you like to submit a PR to fix this?

(P.S. `b1[:n1]` should be enough, the 0 is implied)

**Comment by fohristiwhirl** [comment]
It's so long ago I can't quite remember what I was talking about. I always forget the details of slice stuff. Anyway, I've no desire for credit - if what I wrote was correct, feel free to use it.
