### ISSUE TITLE
Reduce in Collection Functions?

### ISSUE THREAD

**Issue by tleb** [mmcgrana/gobyexample#170]
I believe that [the collection functions page](https://gobyexample.com/collection-functions) is missing a Reduce function. The function would specify the type of the accumulator but I think an example would still be useful. Should it be with an int? Or a struct? Or a slice?

Great resource btw! Very useful to remember how to use something when you come back to the language.

**Comment by mmcgrana** [comment]
I think Reduce is a cool idea but I don't want to add any more functions to the example at this time + I'm not sure how idiomatic Reduce really is in Go vs. more specific functions.

Thank you for the kind words and suggestion though!
