### ISSUE TITLE
Chinese version cannot be visited

### ISSUE THREAD

**Issue by CherryMill** [mmcgrana/gobyexample#173]
Hi, it seems the Chinese version of the Go By Example is down, please help me to look into it:

http://gobyexample.everyx.in

Also, I am wondering whether the output of this translation work is assembled by Simplified Chinese or Traditional? It is a serious question since the two flavor of Chinese shares different char system.

**Comment by everyx** [comment]
@CherryMill I will transfer the Chinese translation project to a new maintainer: @xg-wang , this issue should be be fix soon, sorry about that.

**Comment by CherryMill** [comment]
That is fair, thanks for informing :)

**Comment by xg-wang** [comment]
I will soon submit a pr here once I finished deploying the translated version.

**Comment by mmcgrana** [comment]
Sorry for the delay on this one. Now fixed!
