### ISSUE TITLE
Interfaces: it is better to use pointers

### ISSUE THREAD

**Issue by chenpengcheng** [mmcgrana/gobyexample#178]
The code does not allow a caller to change the state:

func (r rect) area() float64 {
    return r.width * r.height
}

The code does:

func (r rect) area() float64 {
    return r.width * r.height
}

**Comment by mmcgrana** [comment]
I think there are reasons to use pointers or not depending on the circumstance, so I don't think the current approach is obviously wrong. It also aligns with the initial examples in http://jordanorelli.com/post/32665860244/how-to-use-interfaces-in-go. I'm not going to change it right now, but thanks for flagging.
