### ISSUE TITLE
Try to convert to tabs in source

### ISSUE THREAD

**Issue by mmcgrana** [mmcgrana/gobyexample#192]
Then convert to spaces at build-time.

**Comment by eliben** [comment]
I'd suggest keeping it with tabs, per Go convention. Only convert to spaces *during the build*, before `pygmentize` is invoked.

So I'd actually remove the `gbe_to_4spaces` function in tools/format, and instead run the tab->space conversion in Go when reading the source, before passing it to Pygments.

I can take a crack at this - it's annoying that `build` reformats all source files in a non-standard way.

**Comment by mmcgrana** [comment]
Right, that's what I was thinking as well. Fixing this would be welcome!
