### ISSUE TITLE
How about go build with environment variables?

### ISSUE THREAD

**Issue by albscui** [mmcgrana/gobyexample#217]
https://github.com/mmcgrana/gobyexample/blob/ec54a84b0c60ddc8d9684c600f7980bc2847390e/examples/environment-variables/environment-variables.sh#L17

How do we compile a Go binary that captures the environment variables at runtime?
This doesn't seem to work.
```
BAR=2 go build environment-variables.go
```

**Comment by mmcgrana** [comment]
Environment variables are generally run-time settings, not compile-time settings.

Compiling in values set at the command line is beyond the scope of this page (or site), but it looks like it is supported in Go:

https://stackoverflow.com/questions/28459102/golang-compile-environment-variable-into-binary

I haven't used this myself though so can't say for sure.
