### ISSUE TITLE
Add explicit LICENSE file to help GitHub autodetect repo's license

### ISSUE THREAD

**Issue by mbrukman** [mmcgrana/gobyexample#219]
Thanks for making this project! I've enjoyed reading a number of the examples on the site.

According to the [`README.md`][readme]'s section on licensing:

> ### License
> 
> This work is copyright Mark McGranaghan and licensed under a
> [Creative Commons Attribution 3.0 Unported License](http://creativecommons.org/licenses/by/3.0/).
> 
> The Go Gopher is copyright [Renée French](http://reneefrench.blogspot.com/) and licensed under a
> [Creative Commons Attribution 3.0 Unported License](http://creativecommons.org/licenses/by/3.0/).

However, in the absence of an explicit `LICENSE` (or `LICENSE.txt`) file, GitHub cannot autodetect this repo's license as per [this blog post][license-blog-post], and hence it's not displayed in the repo overview.

Would it be possible to add a `LICENSE` file to this repo with the verbatim contents of the [CC-BY-3.0 license][cc-by-3.0] to make this clear?

Thanks!

[readme]: https://github.com/mmcgrana/gobyexample/blob/c43c319d2684b5ad7601e97b5fc2ba54552de4c3/README.md#license
[license-blog-post]: https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/
[cc-by-3.0]: https://creativecommons.org/licenses/by/3.0/legalcode.txt

**Comment by mmcgrana** [comment]
Thanks for the suggestion. Since there are two copyrights at play, the CC-BY-3.0 licensee is very long, and motivated users can easily enough find the licensing information in the readme, I'm not going to add the LICENSE file at this time.
