### ISSUE TITLE
This is not clearly understandable - why do we need to close() here

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mmcgrana/gobyexample#220]
https://github.com/mmcgrana/gobyexample/blob/c43c319d2684b5ad7601e97b5fc2ba54552de4c3/examples/worker-pools/worker-pools.go#L42

**Comment by kitokirisaki** [comment]
There's no particular reason for that, I'd say. He knows that no further actions will be performed with "jobs" after that, so he closes the no longer needed channel.

**Comment by mmcgrana** [comment]
Yes, the example works without this close, it just indicates that no more work will be sent.
