### ISSUE TITLE
Add arrow key navigation?

### ISSUE THREAD

**Issue by cktang88** [mmcgrana/gobyexample#222]
Left/right arrow keys to go to previous/next page would be cool

**Comment by mmcgrana** [comment]
Thank you for the suggestion.

I'm open to this but don't plan to implement it myself. I'm therefore adding a help-wanted label. Notes:

* The implementation would need to be minimal, enough to inline in every page, certainly no third-party javascript.
* I'm 80% sure it'd be good but can't be sure til I try it, so couldn't say for sure until I do.

**Comment by Shivam010** [comment]
Hi @mmcgrana 
I have submitted a PR for the issue, hope it can be merged.
