### ISSUE TITLE
syntax highlighting is incorrect

### ISSUE THREAD

**Issue by nf** [mmcgrana/gobyexample#23]
String literals are highlighted in green. Keywords and some pre-declared identifiers are reddish. The issue I have is with the "some". Highlighting should be consistent.

Here is the list of predeclared identifiers from the spec:
  http://golang.org/ref/spec#Predeclared_identifiers
And keywords:
  http://golang.org/ref/spec#Keywords

I suggest that either pre-declared identifiers should not be highlighted at all (as they may be shadowed by some other declaration), or that they should _all_ be highlighted in a different color to keywords.

**Comment by mmcgrana** [comment]
I'm going to close this because I don't plan to improve the highlighting beyond what's offered by the most recent Pygments package. I'm open to PRs if someone feels really motivated to address this.
