### ISSUE TITLE
Set up CI pipeline to test PRs

### ISSUE THREAD

**Issue by eliben** [mmcgrana/gobyexample#237]
Set up a CI pipeline like [Travis](https://travis-ci.org/) to run `tools/build` on each PR and check there are no errors.

This will catch compile errors, measure issues, generation issues. Checking for the exit code should be sufficient.

**Comment by mmcgrana** [comment]
I'm also wondering if we should check if the output of `tools/build` matches what's checked into `public`?

CI would be useful without that for sure, just using this as a place to discuss this related question (:

**Comment by eliben** [comment]
That's a good idea, I will add that in a followup.

**Comment by eliben** [comment]
Another mental note - double check that we don't send a play.golang request for each run / each file on Travis, with an empty cache - these should hit the sha1 checksum sitting next to the file
