### ISSUE TITLE
Missing Links to HTTP Client and HTTP Server

### ISSUE THREAD

**Issue by timmr99** [mmcgrana/gobyexample#242]
When viewing the [Environment Variables](https://gobyexample.com/environment-variables), the next link is to the [HTTP Clients](https://gobyexample.com/http-clients) and the next link on that page is to [HTTP Server](https://gobyexample.com/http-servers). These links are not on the index page but should be.

**Comment by eliben** [comment]
What do you mean the links are not on the index page? You don't see them on the main https://gobyexample.com/ page? Have you tried force refreshing the browser to avoid cache issues?

**Comment by timmr99** [comment]
Always for get to force refresh. My bad, sorry for the bother!

**Comment by timmr99** [comment]
Closed
