### ISSUE TITLE
How about add an example for crypto/aes?

### ISSUE THREAD

**Issue by donnol** [mmcgrana/gobyexample#245]

**Comment by eliben** [comment]
Thanks for the suggestion, @donnol 

Would you like to sketch a possible example for this?

**Comment by donnol** [comment]
I used to write something like the following:

```go
// Crypto Crypto 
type Crypto struct {
	key string
}

// NewCrypto NewCrypto
// key: 16, 24, or 32 bytes to select AES-128, AES-192, or AES-256.
func NewCrypto(key string) *Crypto {
	var ik string

	keyLen := len(key)
	switch keyLen {
	case 16, 24, 32:
		ik = key
	default:
		panic(fmt.Errorf("Bad key length: %d", keyLen))
	}

	return &Crypto{
		key: ik,
	}
}

// Encrypt Encrypt
func (e *Crypto) Encrypt(money string) (r string, err error) {
	key := []byte(e.key)
	plaintext := []byte(money)

	block, err := aes.NewCipher(key)
	if err != nil {
		return
	}

	ciphertext := make([]byte, aes.BlockSize+len(plaintext))
	iv := ciphertext[:aes.BlockSize]
	if _, err = io.ReadFull(rand.Reader, iv); err != nil {
		return
	}

	stream := cipher.NewCFBEncrypter(block, iv)
	stream.XORKeyStream(ciphertext[aes.BlockSize:], plaintext)
	r = string(ciphertext)

	return
}

// Decrypt Decrypt 
func (e *Crypto) Decrypt(r string) (money string, err error) {
	key := []byte(e.key)
	ciphertext := []byte(r)

	block, err := aes.NewCipher(key)
	if err != nil {
		return
	}

	if len(ciphertext) < aes.BlockSize {
		panic("ciphertext too short")
	}
	iv := ciphertext[:aes.BlockSize]
	ciphertext = ciphertext[aes.BlockSize:]

	stream := cipher.NewCFBDecrypter(block, iv)
	stream.XORKeyStream(ciphertext, ciphertext)
	money = string(ciphertext)

	return
}
```

**Comment by eliben** [comment]
Assigning @mmcgrana for an opinion.

Personally I feel this is a bit too advanced, and is better served by examples in the standard library. The stdlib is large and I don't think we want gobyexample to describe every module in the long run.

My suggestion would be - if the official documentation seems lacking (examples missing or not clear enough) - propose a patch to it to add the better examples

**Comment by mmcgrana** [comment]
Hi, thanks for the suggestion @donnol! I'm not going to add an AES or any crypto-related examples to Go by Example for the foreseeable future. The reason is that crypto is extremely important to get right yet very subtle, so it'd be too easy for us to mess it up or for a user to mis-interpret something. So I'd prefer to leave this to crypto experts in the official docs.
