### ISSUE TITLE
[Help]I have a problem about the .hash file

### ISSUE THREAD

**Issue by LaylaCao** [mmcgrana/gobyexample#250]
I found some .hash file in the example directory, what is this used for?

![6891560833868_ pic_hd](https://user-images.githubusercontent.com/47026836/59658416-1b62cf00-91d6-11e9-9e32-d3bc423ac856.jpg)

PLZ HELP.A FRESH GOLANGER.THANK U  ~

**Comment by eliben** [comment]
The `.hash` files are used by the tooling that generates the website. It ensures that we don't send too many requests to play.golang.org when generating a page - each page has a link to a playground page populated with the code. 

See `tools/generate.go` and search it for `hash` to learn more
