### ISSUE TITLE
Allocation examples

### ISSUE THREAD

**Issue by PeterBocan** [mmcgrana/gobyexample#254]
Hey, I would like to add examples of Allocation, is that possible?

**Comment by eliben** [comment]
Can you please be more specific and explain what you mean by `Allocation`? Sample code would be best

**Comment by PeterBocan** [comment]
You can dynamically allocate objects 3 ways, one of which is less known, but it's all over the place in the examples. 
```go 
func NewPerson() *Person {
    return &Person{Name: "John Doe"} // This is a bit different.
}

func main() { 
   p1 := make([]int, 3) // p1 is []int
   p2 := new(int)  // p2 is *int
   p3 := NewPerson() // the same as p2, but with initialization.

  // there's no explicit way to free up memory due to Golang being
  // a GC language but to remove the last reference to object.
  p3 := nil
}
```
Couldn't be a bit helpful? 

Also, off topic, but when I run `build/tools` my templates get broken.

**Comment by eliben** [comment]
I agree saying something about the `&StructType{...}` allocation would be good, perhaps in the Structs example?

I'd leave the other forms out, `make` comes up naturally in slices and maps, and `new` is fairly esoteric and rarely useful esp. for beginners

Would you like to try your hand at creating a PR for the Structs example adding the allocation somewhere?

**Comment by PeterBocan** [comment]
Yes, once I get the generating working!

**Comment by mmcgrana** [comment]
Just checking through issues - does the most recent merged PR along with the comments above mean we're set here?

**Comment by PeterBocan** [comment]
Yes, we are, @mmcgrana
