### ISSUE TITLE
Adding an example of big.Int

### ISSUE THREAD

**Issue by hesahesa** [mmcgrana/gobyexample#258]
Hi, would it be possible to add an example of big.Int usage to handle arbitrary-precision arithmetic and number parsing?
Thank you!

**Comment by eliben** [comment]
The examples in the `big` package documentation are pretty good. What do you feel is lacking?

**Comment by mmcgrana** [comment]
Yeah I'm probably not going to add this but if someone feels strongly about why we should add it just let us know in the comments.
