### ISSUE TITLE
output from closing channel lesson is not correct!

### ISSUE THREAD

**Issue by Arshiamidos** [mmcgrana/gobyexample#263]
hi  
thanks for your good site .  
i found wrong ouput in [this link](https://gobyexample.com/closing-channels). 
becase goroutin start when need a stall(e.g select, time.sleep, <-chan,...).  
according to your source code it will print 
```go
sent job 1
sent job 2
sent job 3
sent all jobs
received job 1
received job 2
received job 3
received all jobs
```
because it wait for `done`  channel 
![prove](https://user-images.githubusercontent.com/6451804/62323053-ab758300-b4bb-11e9-925d-8b3c03c2bc6d.png)

**Comment by eliben** [comment]
There is no right and wrong here - this output is non-deterministic and depends on concurrency settings, the schedule and so on.
