### ISSUE TITLE
unmatched ouput for atomic example

### ISSUE THREAD

**Issue by Arshiamidos** [mmcgrana/gobyexample#264]
https://gobyexample.com/atomic-counters. 
when run go program 50 times but output is 41419

**Comment by eliben** [comment]
Can you please clarify what is unmatched here?

**Comment by Arshiamidos** [comment]
the output in bottom right

**Comment by Arshiamidos** [comment]
must be 50 not 41..

**Comment by eliben** [comment]
I'm not sure why you think so. The program launches 50 goroutines. Each one sleeps for about a millisecond, and the main goroutine waits for 1 second. This is not accurate science - so the output is usually somewhere between 40,000 and 50,000 and will change from run to run, also depending on the concurrency settings.

**Comment by Arshiamidos** [comment]
my mistake 👎

**Comment by eliben** [comment]
No worries. It occurs to me that the example may be somewhat confusing. Opened #265 to discuss
