### ISSUE TITLE
Consider simplifying the atomics example

### ISSUE THREAD

**Issue by eliben** [mmcgrana/gobyexample#265]
#264 shows a user confusion about the output of the atomics example.

Right now, it's not clear what it demonstrates - that many goroutines can access the same counter without a race? But the output is non-deterministic, so it's hard to be convinced that there isn't a race.

Perhaps we could replace it by something deterministic - goroutines running a known number of increments. Without atomics this would produce gibberish or race errors, with atomics this will count as expected.

**Comment by mmcgrana** [comment]
I'm open to a deterministic example here!
