### ISSUE TITLE
Third column with go's output

### ISSUE THREAD

**Issue by yekm** [mmcgrana/gobyexample#269]
It would be nice to have go's output along the code lines, like this https://yekm.github.io/gobyexample/e/json.html

Index is pretty ugly right now https://yekm.github.io/gobyexample/

Maybe you'll find something interesing in my fork https://github.com/yekm/gobyexample. Build tools rewrited completely so I am not making any pull requests.

**Comment by mmcgrana** [comment]
Hi, this is an interesting idea! Thanks for suggesting it. As Go by Example is pretty stable at this point I'm not going to change the basic formatting, but it could be fun to have a variant like this somewhere on the web if you want to pursue that.
