### ISSUE TITLE
Suggestion for goroutines

### ISSUE THREAD

**Issue by mutantkeyboard** [mmcgrana/gobyexample#279]
I already noticed Mark about this one, but here is the issue: 

We send a lot of Go beginners to your website, and most of them have a habit of clicking the Gopher 
![2019-09-20_10-30](https://user-images.githubusercontent.com/1167494/65311931-c5fddb80-db91-11e9-862c-e9723ff540b9.png)

However on page ->  https://gobyexample.com/goroutines you use `fmt.Scanln()` which will work locally, but won't work on Go playground, since there is no TTY installed. 

My suggestion would be to replace the `fmt.Scanln()` with `time.Sleep(1 * time.Second)`. That way we can get it to work in a more pragmatic way, whether there is a TTY available or not. 

So essentially the new code would look like this: 
```
// A _goroutine_ is a lightweight thread of execution.

package main

import (
	"fmt"
	"time"
)

func f(from string) {
	for i := 0; i < 3; i++ {
		fmt.Println(from, ":", i)
	}
}

func main() {

	// Suppose we have a function call `f(s)`. Here's how
	// we'd call that in the usual way, running it
	// synchronously.
	f("direct")

	// To invoke this function in a goroutine, use
	// `go f(s)`. This new goroutine will execute
	// concurrently with the calling one.
	go f("goroutine")

	// You can also start a goroutine for an anonymous
	// function call.
	go func(msg string) {
		fmt.Println(msg)
	}("going")

        // Instead of fmt.Scanln(), we'd use time.Sleep(1 * time.Second)
	time.Sleep(1 * time.Second)
	fmt.Println("done")
}
```
Result before time: 
![without_time](https://user-images.githubusercontent.com/1167494/65312669-48d36600-db93-11e9-98b4-d9dd7ee7dbd8.png)

And after introducing time: 

![with_time](https://user-images.githubusercontent.com/1167494/65312686-55f05500-db93-11e9-9c44-7c05dce92b92.png)

**Comment by eliben** [comment]
The issue with `time.Sleep` is that it's a really bad practice to "wait for goroutines" to finish. The right thing is to use a `WaitGroup`, but that wasn't introduced yet.

We could put a `time.Sleep` there with a comment to do `WaitGroup` in real code and linking to the later example. @mmcgrana WDYT?

**Comment by mmcgrana** [comment]
> We could put a time.Sleep there with a comment to do WaitGroup in real code and linking to the later example.

Yeah that sounds reasonable to me! I don't think we need to belabor the point in the comment, just a parenthetical mention and link should be fine.

**Comment by eliben** [comment]
> > We could put a time.Sleep there with a comment to do WaitGroup in real code and linking to the later example.
> 
> Yeah that sounds reasonable to me! I don't think we need to belabor the point in the comment, just a parenthetical mention and link should be fine.

Sounds good, sent #280
