### ISSUE TITLE
time.Timer example could be improved

### ISSUE THREAD

**Issue by eliben** [mmcgrana/gobyexample#302]
The timer example starts a goroutine to wait for timer2 to expire, but the main goroutine exits much earlier - so even without the `timer2.Stop`, "Timer 2 stopped" will never be printed.

We should add a sleep at the end of `main` for enough time to actually see that the timer had time to expire had it not been stopped, and add a clarifying comment.

**Comment by mmcgrana** [comment]
Fixed in b32972d.
