### ISSUE TITLE
Example pages won't open as HTML but as text files on localhost

### ISSUE THREAD

**Issue by jan25** [mmcgrana/gobyexample#305]
We have a way to open html files in browsers while development using `open` command(as mentioned here https://github.com/mmcgrana/gobyexample#building). This wouldn't work for example pages as their file suffix isn't `.html`, so they are rendered as text files

**Comment by mmcgrana** [comment]
Yeah good point. Unfortunately I don't know a way to make this work without a local server. Do you?

For now I [fixed](https://github.com/mmcgrana/gobyexample/commit/d6b866d2a1fafd33307b91daa1d641d9bc7c93dc) the README to show how to use a local server to see the build HTML files.

**Comment by eliben** [comment]
I would vote for removing the `open` suggestion entirely, since it's not portable. I don't have an `open` command on the Linux machines I'm usually using, for example.

I just open my browser and go to a `file:///` path for the example, without running `serve`.

**Comment by mmcgrana** [comment]
Good point on `open`, I tweaked the Readme again with this in mind.

**Comment by eliben** [comment]
@jan25 can this issue be closed?

**Comment by jan25** [comment]
@eliben Thanks for suggestions. The Readme looks good now. Let me close this issue
