### ISSUE TITLE
goroutine examples do not match the expected output

### ISSUE THREAD

**Issue by dadish** [mmcgrana/gobyexample#307]
I am new to golang and started with gobyexamples. Thanks a lot for this guide, it's very helpful. Everything is great until it reaches the [goroutines](https://gobyexample.com/goroutines) example. It promises the output to be
```
direct : 0
direct : 1
direct : 2
goroutine : 0
going
goroutine : 1
goroutine : 2
done
```
But my local environment's output and the output from [golang  playground]() is
```
direct : 0
direct : 1
direct : 2
goroutine : 0
goroutine : 1
goroutine : 2
going
done
```
The same goes for [closing-channels](https://gobyexample.com/closing-channels) example. The expected output is
```
sent job 1
received job 1
sent job 2
received job 2
sent job 3
received job 3
sent all jobs
received all jobs
```
But the output from both the local environtment and the [golang playground](https://play.golang.org/p/mkz69rVMHs6) is
```
sent job 1
sent job 2
sent job 3
sent all jobs
received job 1
received job 2
received job 3
received all jobs
```

What am I missing here? Why I can't get the expected output?

My local environment:
OS: MacOS 10.14.6
Go: go1.13.4 darwin/amd64

**Comment by eliben** [comment]
There's nondeterminism here having to do with the concurrency, and the order of the output may change depending on the machine, OS and Go version. We could tweak the comments in these examples to make it clearer folks shouldn't always expect the exact same output.

**Comment by dadish** [comment]
Understood. I'll read about concurrency and nondeterminism more. But yeah, adding some clarifications could prevent confusion. But then again, maybe things start to get clearer when you get further.

Thanks
