### ISSUE TITLE
Add an example of using errgroup, or mention it in the WaitGroup example

### ISSUE THREAD

**Issue by eliben** [mmcgrana/gobyexample#308]
`golang.org/x/sync/errgroup` is a semi-official package for managing multiple goroutines and propertly propagating their errors, with cancellation support via a context.

We should add an example of `errgroup`, or at least mention it in the WaitGroup example - pointing folks to it for more advanced use cases.

**Comment by cirelli94** [comment]
I come here to propose this. It should be very useful, at least a mention!

**Comment by Omid-SH** [comment]
Hi, [This](https://github.com/Omid-SH/Web_Final_Issues/tree/main/%23308/errGroupIssue) may be helpful.
