### ISSUE TITLE
Program go wrong when testing directory functions

### ISSUE THREAD

**Issue by Ty-Chen** [mmcgrana/gobyexample#315]
In the example of directory, I try to run the program but meet a bug in my VS Code.

**cannot use visit (type func(string, os.FileInfo, error) error) as type filepath.WalkFunc in argument to filepath.Walk**

**Comment by eliben** [comment]
This is odd. That code definitely works on Go 1.13, both locally and on the Go Playground -- https://play.golang.org/p/UaeLMS5VQVR

According to the documentation, `WalkFunc` is:

```
type WalkFunc func(path string, info os.FileInfo, err error) error
```

Which matches the type of `visit`.

I'd say something is wrong with your setup.

**Comment by eliben** [comment]
Closing this issue for now, since there has been no response for over a year. Please feel free to reopen the issue if your problem but then provide more details about the exact code sample you're running and what line the error points to, along with your Go version.
