### ISSUE TITLE
Context Example - timeout mismatch between code and description

### ISSUE THREAD

**Issue by jarekdziedzic** [mmcgrana/gobyexample#319]
In the Context example the description says:

> Wait for 3 seconds before sending a reply to the client.

While the code does this:

```
case <-time.After(10 * time.Second):
        fmt.Fprintf(w, "hello\n")
```

I think these should be unified to avoid reader confusion, even if temporary.

**Comment by eliben** [comment]
This was already fixed in https://github.com/mmcgrana/gobyexample/commit/3f8e58ad580b1515d644ec931fe1989c199e4e26

@mmcgrana - I think the site has to be redeployed for the change to take effect.

**Comment by mmcgrana** [comment]
Sorry - deployed!
