### ISSUE TITLE
Statements printed out of order in "Closing Channels" 

### ISSUE THREAD

**Issue by jeremypress** [mmcgrana/gobyexample#322]
Hi, I noticed that the example run command prints out 

```
sent job 1
received job 1
sent job 2
received job 2
sent job 3
received job 3
sent all jobs
received all jobs
```

But when I run the same code I see
```
sent job 1
sent job 2
sent job 3
sent all jobs
received job 1
received job 2
received job 3
received all jobs
```

Could this be due to my go version? I'm on 1.13
You can try it here https://repl.it/@jeremypress/30-closing-channels, and I also verified it locally.

**Comment by eliben** [comment]
Please see #307
