### ISSUE TITLE
Regular expressions - MustCompile

### ISSUE THREAD

**Issue by gren236** [mmcgrana/gobyexample#325]
Hello! I'm still learning, but this comment on https://gobyexample.com/regular-expressions page left me confused:

> When creating constants with regular expressions you can use the MustCompile variation of Compile. A plain Compile won’t work for constants because it has 2 return values.

You still won't be able to create a constant using this function and this pattern is used for **global variables** as mentioned in source code comment:

> It simplifies safe initialization of global variables holding compiled regular expressions.

So, is it a comment inaccuracy or am I wrong?

**Comment by eliben** [comment]
Thanks for the report. You are correct, regexps cannot be constants. Would you like to send a PR to fix the comment?

**Comment by gren236** [comment]
Sure! I'll do it as soon as I get to my workplace :)

**Comment by mmcgrana** [comment]
Fixed in master - thanks!
