### ISSUE TITLE
The interface example should use public methods

### ISSUE THREAD

**Issue by TeXitoi** [mmcgrana/gobyexample#327]
The example Interfaces use private name for the methods. 99% of the times, the methods of an interface are Public, using private method is useful, but a niche use case.

To minimize strange error from the compiler when using private methods in interfaces, I propose to use public method in the example.

Strange error message from https://stackoverflow.com/questions/26181271/is-it-possible-to-implement-an-interface-with-unexported-methods-in-another-pack:

```
./main.go:2: cannot use adapter (type accountingsystem.Adapter) as type accounting.IAdapter in argument to accounting.SetAdapter:
accountingsystem.Adapter does not implement accounting.IAdapter (missing accounting.getInvoice method)
    have accountingsystem.getInvoice() error
    want accounting.getInvoice() error
```

**Comment by eliben** [comment]
I think that unexported names for gobyexample examples is appropriate. These are small `main.go` binaries, which aren't importable packages.

**Comment by TeXitoi** [comment]
https://tour.golang.org/methods/9

The go tour use a public method in its interface example, and is on the same kind of gobyexample. I propose such a change because a college lost a few hours on it by copying this exact example.

Now, that's up to you, I will not insist anymore.
