### ISSUE TITLE
Clarify filename requirements for "go test"

### ISSUE THREAD

**Issue by z3ntu** [mmcgrana/gobyexample#339]
See https://github.com/mmcgrana/gobyexample/blob/master/public/testing#L74-L78

> Typically, the code we’re testing would be in a source file named something like intutils.go, and the test file for it would then be named intutils_test.go.

This doesn't mention the **requirement** (at least for simple cases, I'm not too sure) that the file is named `*_test.go`. 

`go help test` clarifies this:

> 'Go test' recompiles each package along with any files with names matching the file pattern "*_test.go".

**Comment by eliben** [comment]
It's not clearly what the specific change requested here is, could you please clarify? (or submit a PR with the proposed change)

**Comment by z3ntu** [comment]
It wasn't clear for me that the file with the tests **must** be named `foobar_test.go` ; other languages don't have such a requirement so I thought it was just a convention that people use instead of a fixed requirement.

**Comment by mmcgrana** [comment]
I don't feel strongly about this one, defer to you @eliben as author of the example.

**Comment by eliben** [comment]
I believe the current wording is sufficient. The main goal of gobyexample is to provide short, working, copy-pasteable examples. Precisely describing all nuances of the language and its tooling is not. Besides, the current wording could be read as implying the "must" aspect.
