### ISSUE TITLE
Add explanation of empty interface, with examples

### ISSUE THREAD

**Issue by rlunde** [mmcgrana/gobyexample#340]
I frequently come across code that uses empty interfaces, type assertions, and type switches. For example, the Marshal and Unmarshal functions in encoding/json take empty interface argument.  Type assertions are sometimes used with errors, since specific types of errors might be handled specially, but there are a lot of cases where type assertions or type switches are used with empty interfaces as well. 

Ideally, I think this would be 3 examples.

**Comment by Omid-SH** [comment]
Hi, [This](https://github.com/Omid-SH/Web_Final_Issues/tree/main/%23340/interfaceIssue) may be helpful.

**Comment by eliben** [comment]
@rlunde doesn't the example in https://gobyexample.com/switch cover what you want, at least partially?

```
    whatAmI := func(i interface{}) {
        switch t := i.(type) {
        case bool:
            fmt.Println("I'm a bool")
        case int:
            fmt.Println("I'm an int")
        default:
            fmt.Printf("Don't know type %T\n", t)
        }
    }
    whatAmI(true)
    whatAmI(1)
    whatAmI("hey")
```

This shows `interface{}` and a type switch.

Moreover, the errors example at https://gobyexample.com/errors shows a type assertion specifically with errors.
I'm going to close this issue for now, but please feel free to reopen it if you feel there's some crucial information missing from these examples.

@Omid-SH to contribute changes to this repository, please open a Pull Request for review.
