### ISSUE TITLE
Proposal: Upgrading examples from using `io/util` (once 1.17 ships)

### ISSUE THREAD

**Issue by selahaddinh** [mmcgrana/gobyexample#343]
Hey everyone,
As you may know, there are talks of deprecating `io/util` for go v1.16. 
More on this can be found: 
https://github.com/golang/go/issues/40025
https://github.com/go-critic/go-critic/issues/1019
https://github.com/golang/go/issues/42026

I think, upgrading the examples from using `io/util` would be beneficial for newcomers to learn the state-of-art practices.

**Comment by eliben** [comment]
Sounds good, given that the replacements work on the current and previous version (e.g. if they go in right now, on versions 1.15 and 1.14 at least). Feel free to send a PR

**Comment by selahaddinh** [comment]
I believe, this needs to wait version 1.17 then.

**Comment by eliben** [comment]
Go 1.17 will be released in August 2021. At that point we should be able to safely replace uses of `ioutil` with `os`, where applicable.

At this time, gobyexample uses the following functions from `ioutil` in examples:

* WriteFile
* ReadDir
* ReadAll
* TempFile
* TempDir
* ReadFile

**Comment by eliben** [comment]
Since we keep getting duplicate reports, I went ahead and created https://github.com/mmcgrana/gobyexample/pull/374 which implements this - that PR will be updated and reviewed/landed once Go 1.17 ships in August 2021.
