### ISSUE TITLE
Go not only support methods on struct types

### ISSUE THREAD

**Issue by enkeyz** [mmcgrana/gobyexample#356]
https://gobyexample.com/methods

It says, "Go supports methods defined on struct types." But it isn't exactly true, because Go supports methods on ANY defined type.

```go
package main

type Number int

func (n *Number) Double() {
	*n *= 2
}

func main() {
	number := Number(4)
	number.Double()
}
```

**Comment by eliben** [comment]
*Go supports methods defined on struct types* says just what it says, it doesn't say Go does not support methods on other types! The goal of gobyexample.com is not to be an alternative for the Go spec, so IMHO this is WAI.

**Comment by eliben** [comment]
Closing this. Please reopen with additional reasoning if you disagree with my reply.
