### ISSUE TITLE
Structs - local variables and pointers

### ISSUE THREAD

**Issue by meerasndr** [mmcgrana/gobyexample#361]
The structs page says:
` You can safely return a pointer to local variable as a local variable will survive the scope of the function. `
Is this right? 
Or, is it meant to be?
`You can safely return a pointer to local variable as a _pointer_ will survive the scope of the function.`

Thanks.

**Comment by eliben** [comment]
I believe the original meaning of the comment is correct.

For reference, please see https://golang.org/doc/effective_go (search for "return the address" in that page), or discussions like https://stackoverflow.com/questions/13715237/return-pointer-to-local-struct

If you still think the current wording is not correct, please explain why.

**Comment by meerasndr** [comment]
Thanks for the response. This was helpful.
