### ISSUE TITLE
Example "Reading Files" shouldn't be using io/ioutil

### ISSUE THREAD

**Issue by ResamVi** [mmcgrana/gobyexample#362]
The example in https://gobyexample.com/reading-files
still imports ioutil:
```go
import (
    "bufio"
    "fmt"
    "io"
    "io/ioutil"
    "os"
)
```

As of Go 1.16 the funcionality functionality is provided by package io or package os (see https://golang.org/pkg/io/ioutil/)
and would have to look something like this

```go
dat, err := os.ReadFile("/tmp/dat")
check(err)

fmt.Print(string(dat))
```

**Comment by eliben** [comment]
You're right. This is tracked in https://github.com/mmcgrana/gobyexample/issues/343
