### ISSUE TITLE
Why use a pointer i.e. &sync.Mutex{} in Mutexes example 

### ISSUE THREAD

**Issue by mannharleen** [mmcgrana/gobyexample#364]
https://github.com/mmcgrana/gobyexample/blob/58e66a8103f6820ec554578b543a2c94602273c6/examples/mutexes/mutexes.go#L22

Change `&sync.Mutex{}` to `sync.Mutex{}`. It is clearer, and doesn't impact the logic. (OR Am I wrong?)

**Comment by mmcgrana** [comment]
Hmm I guess I was thinking that since Mutexes can't be copied (https://golang.org/pkg/sync/#Mutex) it needs to be a reference and not a value. But now I'm not sure. @eliben do you have any thoughts here?

**Comment by eliben** [comment]
It's true that mutexes should not be copied (e.g. see https://eli.thegreenplace.net/2018/beware-of-copying-mutexes-in-go/), but in this case I don't believe the `mutex` variable is copied. Closures capture variables by reference.

So we could remove the `&` here.

That said, the example in `mutexes.go` is rather complicated, and it's hard to even say whether the result is correct or not if we modify the mutex (other than lack of race detection errors). IMHO we could change it to a much simpler example that is both trivial to verify and demonstrates proper embedding of a mutex, with pointer receivers to discuss the by value / by reference change:
```

package main

import (
  "fmt"
  "sync"
  "time"
)

type Container struct {
  sync.Mutex
  counters map[string]int
}

func (c *Container) inc(name string) {
  c.Lock()
  defer c.Unlock()
  c.counters[name]++
}

func main() {
  c := Container{counters: map[string]int{"a": 0, "b": 0}}

  doIncrement := func(name string, n int) {
    for i := 0; i < n; i++ {
      c.inc(name)
    }
  }

  go doIncrement("a", 100000)
  go doIncrement("a", 100000)

  // Wait a bit for the goroutines to finish
  time.Sleep(300 * time.Millisecond)
  fmt.Println(c.counters)
}
```
