### ISSUE TITLE
Contributing Polish Translation

### ISSUE THREAD

**Issue by baduker** [mmcgrana/gobyexample#369]
Hi there!

I've prepared a Polish translation of the project. It's available here - https://gowprzykladach.pl and the fork is here https://github.com/baduker/gobyexample

Let me know if you'd like to add it to the Contributor Translations, so I can create a Pull request.

**Comment by baduker** [comment]
Cool! I'll make a PR soon.

**Comment by eliben** [comment]
Note that I've closed the attached PR since it was not responded to for ~2 months. 

Leaving the issue open and unassigned in case someone wants to contribute a Polish translation link.

**Comment by eliben** [comment]
Will close this issue for now, due to the lack of interest. Feel free to reopen if this becomes relevant again.
