### ISSUE TITLE
Add example of container/heap

### ISSUE THREAD

**Issue by Clay2018** [mmcgrana/gobyexample#373]
[heap.txt](https://github.com/mmcgrana/gobyexample/files/6565478/heap.txt)

**Comment by eliben** [comment]
I'll note that the `container/heap` package already has a couple of pretty good [examples in its docs](https://pkg.go.dev/container/heap), and that it's a fairly obscure package most Go programmers will never use. So IMHO it doesn't belong on gobyexample

**Comment by Clay2018** [comment]
Thanks for your explanation
