### ISSUE TITLE
Proposal: Add an assigment for each lesson to improve learning process

### ISSUE THREAD

**Issue by dandaka** [mmcgrana/gobyexample#378]
## Now

A lesson shows on example Go concept. This does not stimulate a student to write code

## Improvement

Every lesson has an assignment with a hidden answer. A student is encouraged to solve a task with code. He has an option to compare the author's solution with his.

**Comment by eliben** [comment]
Thanks for the suggestion, @dandaka 
This is proposing a significant change to the website. I'm not sure this is a direction gobyexample is pursuing, but will assign @mmcgrana to get his thoughts.

**Comment by mmcgrana** [comment]
Yeah I am not inclined to add this to the site at this time, sorry!
