### ISSUE TITLE
string-formatting: move outputs closer to code

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mmcgrana/gobyexample#382]
https://github.com/mmcgrana/gobyexample/blob/master/examples/string-formatting/string-formatting.go

![image](https://user-images.githubusercontent.com/3514015/129952647-2e37983c-7837-4ee6-96ba-6bd3000f52e1.png)

Because now we need to scroll and map in our heads order with printed result.

**Comment by eliben** [comment]
This could be similar to #198

**Comment by eliben** [comment]
#391 landed
