### ISSUE TITLE
Implement mobile markup

### ISSUE THREAD

**Issue by vitaly-zdanevich** [mmcgrana/gobyexample#392]
Because now we have this:

![Screenshot_2021-09-07-15-45-09-906_org mozilla firefox](https://user-images.githubusercontent.com/3514015/132346946-7a724f76-01a8-4e07-aa8b-b09b746d709f.jpg)

**Comment by eliben** [comment]
Can you clarify what this issue is proposing/asking for?

**Comment by vitaly-zdanevich** [comment]
Text is too small, it should be larger.

**Comment by eliben** [comment]
IMHO it works fine as-is. In landscape mode gobyexample.com looks pretty well, and of course zooming in/out is trivial on mobile. The alternative would be lowering the information density, which has downsides.
