### ISSUE TITLE
A secret chapter

### ISSUE THREAD

**Issue by kwarabei** [mmcgrana/gobyexample#435]
According to the issue #418, the book changed the SHA1 example to be the SHA256 example. The [SHA1 example](https://gobyexample.com/sha1-hashes) is still available, not present in the table of contents though. Is that some kind of backward compatibility, or the SHA1 page should be deleted?

**Comment by eliben** [comment]
No, just didn't clean up the output in storage. It should be removed now (modulo cache propagation)
