### ISSUE TITLE
Proposal: Add a little more info about short variable declaration

### ISSUE THREAD

**Issue by slab713** [mmcgrana/gobyexample#438]
I think it would be helpful if there'd be another sentence about how short variable declaration with `:=` is not possible outside of a function (including `main()`).

https://gobyexample.com/variables
https://go.dev/tour/basics/10

**Comment by eliben** [comment]
Feel free to propose a PR with the change

**Comment by grejojoby** [comment]
Have done the suggested changes in PR: #455 .
