### ISSUE TITLE
Proposal: Improve the clarity of https://gobyexample.com/non-blocking-channel-operations

### ISSUE THREAD

**Issue by aaash99999** [mmcgrana/gobyexample#447]
It might sound trivial, but despite the explanations in the comments, I am struggling with this example.  Can perhaps a part two (second example, or an additional part be added where the messages are processed?  Right now I am a still a bit lost :(

**Comment by eliben** [comment]
Can you explain which part is unclear?

To be honest, gobyexample is not meant as an end-to-end tutorial for Go. You should use additional resources to learn the language and the different working parts.

**Comment by aaash99999** [comment]
Hi eliben, and firstly thanks so much for your help and the work you do on this invaluable resource.  Perhaps the non-blocking example is a poor example of where I am struggling.  

Running the code in the example works as expected, but I tried to modify the program to print additional messages sent via a range statement over a slice of strings, instead of just a a single string value.  

After consulting: https://gobyexample.com/waitgroups and https://gobyexample.com/channel-synchronization I have a version that 'works', but looks like it is most likely terrible code :(  A better example with some annotations might help.  I'm not sure, what are your thoughts?

'Working' version:
https://go.dev/play/p/oJ1Z0WuCEjf


Many thanks,
Ash

**Comment by eliben** [comment]
Happy to hear that you're finding this resource useful.

I don't see a specific crisp example here that could be added - but if you have an idea, please open a new issue and say what exactly the example should do.

For general help with Go questions I recommend asking the golang-nuts@ mailing list
