### ISSUE TITLE
Suggestion: Separate code from content to avoid copying of content while trying to copy code

### ISSUE THREAD

**Issue by Ranjeetk489** [mmcgrana/gobyexample#448]
I have started learning about Go and i am using Go by example to get familiar with the syntax and to get a overview of concepts in Go. While going through different articles i have noticed that whenever i try to copy some part of code i end up selecting the content as well. Which isn't the type of behavior i was expecting. It would be really cool if it could be fixed as i feel many of the learners might be facing the same issue while going through the website. Also if is to be addressed i'd like to volunteer for the changes.

![issue ss](https://user-images.githubusercontent.com/49064698/194696631-197bebb4-1dc6-45a2-938b-1d1687881fb5.png)

**Comment by eliben** [comment]
There are two easy ways to copy code already:

1. Click on the copy-code icon on the top right of the code pane
2. Click on the gopher next to it, which brings you to the same code on the playground - then you can copy any part you want

If you're really inclined to, you can try working on a PR that will support what you say in the main view, but no promises about accepting it. This is ultimately something that's used rarely (copy portions) and saves the user maybe 1 second, so I will accept an alternative solution if it seems very simple and safe.
