### ISSUE TITLE
mutex unlock out of order

### ISSUE THREAD

**Issue by jwilliamson1** [mmcgrana/gobyexample#459]
This is in your mutex example. Based on mutexes in other languages I think

`c.mu.Lock()
defer c.mu.Unlock()
c.counters[name]++`

should be

`c.mu.Lock()
c.counters[name]++
defer c.mu.Unlock()`

**Comment by eliben** [comment]
Please see https://gobyexample.com/defer and https://go.dev/ref/spec#Defer_statements
