### ISSUE TITLE
Could you add an example for recover()?

### ISSUE THREAD

**Issue by LarryBattle** [mmcgrana/gobyexample#46]
Here's an example I wrote up for recover(). It would be nice if you included this in your examples.

```
package main

import "fmt"

func gandalf( doTalkTo bool ){
    defer catch()
    if(doTalkTo){
        // Panic stops execution of the current function and stops unwinding the stack, calling an deferred functions along the way.
        panic("You shall not pass!")    
    }
}
// catch() must be called as a deferred 
func catch(){
    // recover() regains control over the program execution when panic() is called.
    // recover() returns is the argument passed from panic()
    if r := recover(); r != nil {
        fmt.Println("Error:", r)
    } else {
        fmt.Println("No problems occurred")
    }
}
func main() {
    gandalf(true)
    gandalf(false)
    //unwinds to the top of the stack and ends the program
    panic("Where am I going?");
}

// Output:
// Error: You shall not pass!
// No problems occurred
// panic: Where am I going?
// goroutine 1 [running]:
// main.main()
```

Demo: http://play.golang.org/p/xu9Jd1YI0T

More information here:
<a href="http://golang.org/doc/effective_go.html#recover">Effective Go - The Program Language</a>

**Comment by mmcgrana** [comment]
Sorry I'm only responding to this issue now /:

I'm actually not planning to add any more sections to Go by Example. `recover` is a very reasonable idea but due to personal bandwidth limitations I need to not increase the scope of the site at this point. Sorry!

**Comment by kilaka** [comment]
Can we reopen this as the community have grown and we can/want to help :)

**Comment by mmcgrana** [comment]
Yes we're in a better position to consider this now!

**Comment by eliben** [comment]
An example for `recover` sounds like a good idea, but I'd personally prefer something simpler than the proposal in this issue.

**Comment by kilaka** [comment]
I've created a PR using a fork.
Have two problems which I hope you have the knowledge to fix them quickly:
1. Some strange auto-generated chars, which changed from `\x3D` to `\u003D`, causing a lot of files to look as if they were changed, but actually were not.
2. Misalignment between explanation and code.

https://github.com/mmcgrana/gobyexample/pull/344

@eliben, @mmcgrana, can you see if it looks OK?
Feel free to change/comment.

**Comment by eliben** [comment]
Thanks for discussion. I ended up adding a simplified example (see linked commit). Please open an issue/PR if you have questions or suggestions about the new example.
