### ISSUE TITLE
Group articles

### ISSUE THREAD

**Issue by hashrock** [mmcgrana/gobyexample#465]
I was working on a redesign of Deno by example (inspired by Go by example), and it would be good to group the articles over here as well.

https://github.com/denoland/denobyexample/issues/63

![image](https://user-images.githubusercontent.com/3132889/224941208-4e19250a-e62f-45a9-bba1-f6007d7f2bf9.png)

**Comment by eliben** [comment]
interesting idea. I have a feeling that for gobyexample things would be different because the large majority of the pages are about the language (Deno is different in this respect since it's not a language per se).

**Comment by eliben** [comment]
Can you suggest how a potential grouping would look?

**Comment by bartekpacia** [comment]
I, for once, like the simplicity of what it looks like currently :)

**Comment by hashrock** [comment]
Indeed, the current design seems good enough
