### ISSUE TITLE
missing "package" explainion

### ISSUE THREAD

**Issue by CrackerJackMack** [mmcgrana/gobyexample#48]
Been re-enforcing my readings of go with these examples (excellent btw). But there are no concrete examples of what the package declaration does or how that affects things.  It would be great to show how writing your own package works in conjunction with "package main".

Thanks again.

**Comment by bcomnes** [comment]
I just noticed this too.

**Comment by mmcgrana** [comment]
I'm sorry it took so long to get back on this /:

I'm not planning to expand the scope of Go by Example any further at this point. While agree pacakges are a good thing to learn about, we won't be covering them on the site. Sorry!
