### ISSUE TITLE
stateful goroutines clarification

### ISSUE THREAD

**Issue by megaadam** [mmcgrana/gobyexample#480]
A friendly suggestion in the `git patch` below. Regardless of your verdict - thanks for an awesome Golang site. Cheerz.

From 84f0d08faee4fa2720756809b5645f6fa40abad3 Mon Sep 17 00:00:00 2001
From: Adam Horvath <adam.horvath@edgeware.tv>
Date: Tue, 18 Jul 2023 12:58:28 +0200
Subject: [PATCH] stateful-goroutines

I humbly suggest to remove the channel from `type writeOp`
Motivation:
- clearer illustration of the [purpose of the] syncronisation mechanism
- no race condition can occur in the select-loop
- no result is is needed by the writer loop [unlike the reader loop]
Ballpark results on my laptop:
- writeOps count increased by ~ 5% (gut feeling by staring at the
  numbers)
- readOps count increased by ~ 2%

If this is a bad idea, then perhaps a comment clarifying the need for
waiting on writes would be good.
---
 examples/stateful-goroutines/stateful-goroutines.go | 12 ++++--------
 1 file changed, 4 insertions(+), 8 deletions(-)

diff --git a/examples/stateful-goroutines/stateful-goroutines.go b/examples/stateful-goroutines/stateful-goroutines.go
index 11a6f08..1e1dff4 100644
--- a/examples/stateful-goroutines/stateful-goroutines.go
+++ b/examples/stateful-goroutines/stateful-goroutines.go
@@ -29,9 +29,8 @@ type readOp struct {
 	resp chan int
 }
 type writeOp struct {
-	key  int
-	val  int
-	resp chan bool
+	key int
+	val int
 }
 
 func main() {
@@ -63,7 +62,6 @@ func main() {
 				read.resp <- state[read.key]
 			case write := <-writes:
 				state[write.key] = write.val
-				write.resp <- true
 			}
 		}
 	}()
@@ -93,11 +91,9 @@ func main() {
 		go func() {
 			for {
 				write := writeOp{
-					key:  rand.Intn(5),
-					val:  rand.Intn(100),
-					resp: make(chan bool)}
+					key: rand.Intn(5),
+					val: rand.Intn(100)}
 				writes <- write
-				<-write.resp
 				atomic.AddUint64(&writeOps, 1)
 				time.Sleep(time.Millisecond)
 			}
-- 
2.34.1

**Comment by eliben** [comment]
This patch is unreadable. Please send a PR via GitHub instead. Thanks in advance
