### ISSUE TITLE
Various errors in code?

### ISSUE THREAD

**Issue by randomouscrap98** [mmcgrana/gobyexample#484]
I'd like to preface with the fact that I'm not a go programmer, I'm just learning.

In the mutex example, https://github.com/mmcgrana/gobyexample/blob/master/examples/mutexes/mutexes.go#L24
It seems wrong to release the mutex immediately after grabbing it and before modifying the counter. Shouldn't the `Unlock()` happen after the counter increment?

In the waitgroups example, https://github.com/mmcgrana/gobyexample/blob/master/examples/waitgroups/waitgroups.go#L41
It seems wrong to mark the job as done before you even execute the job itself. In later examples, you call `Done()` after the job. In this example, it seems like it's possible for the wait group to be fully decremented before all the jobs are complete.

**Comment by eliben** [comment]
Please see https://gobyexample.com/defer

**Comment by randomouscrap98** [comment]
I'm sorry for the confusion. This brings up a different point: you use Defer before it is explained. People used to other languages will assume it is an error to release a mutex before modifying the protected resource. Since go presents itself as a procedural language, I think it is uncommon to come across a seemingly innocuous line of code that executes out of order. It would be like using the "go" keyword before explaining it and expecting people to know that it creates a coroutine. Considering this, I think it'd be good to have Defer come before the examples which use it.
