### ISSUE TITLE
Add content to if else example

### ISSUE THREAD

**Issue by SandeshGC** [mmcgrana/gobyexample#493]
The 'else' keyword should be on the same line as the closing braces of the if statement. This information would be useful for beginners.
The url is: [https://gobyexample.com/if-else](https://gobyexample.com/if-else)

This is not accepted in go:
![image](https://github.com/mmcgrana/gobyexample/assets/59115123/d10c6a42-4159-41e3-988e-8675a4a5ac80)

This is required:
![image](https://github.com/mmcgrana/gobyexample/assets/59115123/83f81752-8a2b-4ebf-b588-75243b13adcd)

So, I think this should be included in the page as an example.

I would like to work on this issue but I am not familiar with the project.

**Comment by eliben** [comment]
I'm not sure I understand your suggestion. The page at https://gobyexample.com/if-else already formats the `else` correctly. What would you change?

**Comment by SandeshGC** [comment]
Yes the information is correct as it is in the page. But I think the additional information that the "else" keyword should be at the same line as the ending curly braces "}" of the "if" statement would be useful for beginners.

I mean that this does not work in go:
```go
 if <condition> {
        //code to run
}
else {
        //code to run 
}
```
Here the "else" statement does not start at the same line where the if statement ends. I mean that the "else" keyword should be in the same line as the } of the previous block.

This is required in go:
```go
if <condition> {
        // code
} else {
        // code
}```

See the position of the ending curly braces of "if block" and the "else" keyword, they should be in the same line. This may not be a big issue but it would be helpful for beginners like me. I did not know there was such rule in the if-else staement in golang for  about a week of starting to learn it.

Is it clear?

**Comment by SandeshGC** [comment]
https://www.learn-golang.org/en/If-Else
See the "else statement" section
![image](https://github.com/mmcgrana/gobyexample/assets/59115123/59659023-9be1-4e79-b5d4-944c145076e2)

I think this would be a useful information for those learning golang.

**Comment by eliben** [comment]
It seems to me OK as it is now. Go code almost always goes through an autoformatter than fixes this
