### ISSUE TITLE
Feature Request - If/Else logical operators

### ISSUE THREAD

**Issue by ganjarsetia** [mmcgrana/gobyexample#494]
I think its better to add [logical operator](https://go.dev/ref/spec#Logical_operators) at https://gobyexample.com/if-else It really helpful for beginner.
Sorry I cant create PR, because I'm not good explaining in English.

Example 
```go
var a bool = true
var b bool = false
if ( a && b ) {
  fmt.Printf("Line 1 - Condition is true\n" )
}
```

If this not suitable for gobyexample, you can close this issue

**Comment by eliben** [comment]
Thanks for the suggestion
