### ISSUE TITLE
Sidebar/expandable table of contents?

### ISSUE THREAD

**Issue by pritster5** [mmcgrana/gobyexample#495]
Love this guide but I fidn myself wanting to go back to prior sections without having to go back one at a time through the examples in reverse. 

Is it possible to add a table of contents as a sidebar so users can quickly jump to a topic they're interest in?

**Comment by eliben** [comment]
See the note at https://github.com/mmcgrana/gobyexample/blob/master/CONTRIBUTING.md

**Comment by pritster5** [comment]
"We're not going to change the navigation of the site, in particular adding a "previous section" link or an "index" link other than the one on the title text."

Why?
