### ISSUE TITLE
Allow copying

### ISSUE THREAD

**Issue by darkBuddha** [mmcgrana/gobyexample#496]
Hi, currently this happens:

![Screenshot 2023-11-04 at 10 00 10](https://github.com/mmcgrana/gobyexample/assets/3326929/6eba4a8b-9dd0-46d9-9312-6e271b291d2b)

**Comment by eliben** [comment]
Yes, that's now the site layout works. You can either click the copy icon on the top-right corner of the grey code window, or click the gopher which leads you to the playground - there you can copy parts of the code.
