### ISSUE TITLE
Go by Example: For - cannot range over X (untyped int constant)

### ISSUE THREAD

**Issue by DiiBBz** [mmcgrana/gobyexample#509]
Hi!

I believe the code listed in https://gobyexample.com/for causes an error. When copy pasting the code into a `main.go` file and running the code by `go run main.go` I get two errors instead of the assumed output seen in on the left side of the code.

Output:
```
# command-line-arguments
./main.go:17:20: cannot range over 3 (untyped int constant)
./main.go:26:20: cannot range over 6 (untyped int constant)
```

Go version: `go version go1.21.7 darwin/arm64`

**Comment by eliben** [comment]
Please upgrade to Go 1.22!
