### ISSUE TITLE
Time formatting example does not compile

### ISSUE THREAD

**Issue by halesyy** [mmcgrana/gobyexample#512]
https://gobyexample.com/time-formatting-parsing

There are warnings on the `e` values not used. I replaced them with `_`.

Further, the code does not compile due to the free `=` at the bottom of the code. I adjusted this to `:=` which prints the error:

```go
package main

import (
	"fmt"
	"time"
)

func main() {
    p := fmt.Println

    t := time.Now()
    p(t.Format(time.RFC3339))

    t1, _ := time.Parse(
        time.RFC3339,
        "2012-11-01T22:08:41+00:00")
    p(t1)

    p(t.Format("3:04PM"))
    p(t.Format("Mon Jan _2 15:04:05 2006"))
    p(t.Format("2006-01-02T15:04:05.999999-07:00"))
    form := "3 04 PM"
    t2, _ := time.Parse(form, "8 41 PM")
    p(t2)

    fmt.Printf("%d-%02d-%02dT%02d:%02d:%02d-00:00\n",
        t.Year(), t.Month(), t.Day(),
        t.Hour(), t.Minute(), t.Second())

    ansic := "Mon Jan _2 15:04:05 2006"
    _, e := time.Parse(ansic, "8:41PM")
    p(e)
}```

**Comment by eliben** [comment]
Running the example locally works for me. It also works on the playground (https://go.dev/play/p/BoZYtr_2j66) -- link taken from the sample itself.

Can you describe the steps you perform to see the issue?

**Comment by lacamera** [comment]
Did you try to compile it? Sounds like an issue with your editor/setup as the compiler err's on unused variables.
Which LSP are you using?

The example itself is correct though (as mentioned above).
