### ISSUE TITLE
Adding  Go version requirement to certain new features in the language.

### ISSUE THREAD

**Issue by Bakri-Hmouda** [mmcgrana/gobyexample#532]
Hello!

I have noticed that on the `For` page example, the following code example will throw a compiler error if you are using a Go version below `1.22`.

Can we mention in a code comment that users need to update their Go version to try the code snippet?

Thank you!

```go

//cannot range over 3 (untyped int constant)compiler[InvalidRangeExpr]
	for i := range 3 {
		fmt.Println("range", i)
	}
```

**Comment by eliben** [comment]
Thanks. I've added a note in the index page (text on top)
