### ISSUE TITLE
translating to Arabic

### ISSUE THREAD

**Issue by MrAbdul** [mmcgrana/gobyexample#534]
Hi, 
i love the go by example and its so straight forward and explains topics very clearly.
i would like to translate it to Arabic, i have gotten started and understand how to do it. 
however, the generator seems to not handle RTL languages correctly, and i can't name the files Arabic names so they work in the list and title.

my question is, can i edit the template example.tmpl and the css so it can handle the RTL knowing that it wont work for building LTR?
and can i make changes to generate.go so it is able to handle Arabic language in the examples.txt and can map it correctly to the code files?
i believe my edit will be breaking for non RTL languages (which is most languages), would that be ok? since its on my own fork?
or should i make the edit in a way that can take options when building the static site to distinguish between RTL and LTR.

thank you for the awesome resource, and appreciate your input

**Comment by eliben** [comment]
This repository is [licensed fairly liberally](https://github.com/mmcgrana/gobyexample?tab=readme-ov-file#license) - you're free to make any changes you see fit in your own fork; does that answer your question?
