### ISSUE TITLE
Nothing big just a typo

### ISSUE THREAD

**Issue by OverYourSkill** [mmcgrana/gobyexample#547]
I was coding and then I noticed that there was a typo on the website in the Enums example.
The code works fine. Its just the word unknown at the end has a typo as you can see in the Screenshot.

### Screenshot
![image](https://github.com/user-attachments/assets/fffc6c42-bd20-483b-99f0-4c4a1abde2e5)

### Direct link to the website
https://gobyexample.com/enums

**Comment by eliben** [comment]
This typo has already been fixed at head. Will redeploy website to be sure it's rendered
