### ISSUE TITLE
Improve explanation of constructor functions for structs

### ISSUE THREAD

**Issue by ThomasJunk** [mmcgrana/gobyexample#550]
Under `https://gobyexample.com/structs` is the function `newPerson` which constructs a new person.

While reading I stumbled upon the explanation 

> You can safely return a pointer to local variable as a local variable will survive the scope of the function.

which I didn't understand. 

From my unterstanding it should read

> You can safely return a pointer to a local variable because the pointer creates a reference to the local variable which will survive garbage collection as long as the pointer itself isn't garbage collected.

Is my unterstanding correct?

**Comment by eliben** [comment]
Yes. Admittedly the text could be clearer. I think your alternative is a bit too verbose, though

**Comment by ThomasJunk** [comment]
Alternatively I could think of: 

> Returning a pointer to the local variable makes it survive the scope of the function.

What do you think?

**Comment by eliben** [comment]
Thanks for your suggestion - I've pushed a clarification. We could say more but the goal here is not a complete tutorial.
