### ISSUE TITLE
Testing and Benchmarking - main module error

### ISSUE THREAD

**Issue by Masked-Code** [mmcgrana/gobyexample#561]
While following the Testing and Benchmarking section of Go By Example, and running the  ```go test -v```, ```go test -bench=.```, or even ```go build -o TestingAndBenchmarking.exe testingAndBenchmarking.go``` I get the following error: ```go: cannot find main module```. 

Very new to Go and reporting issues in github, so if this is the incorrect format or if I am making a simple mistake please let me know. Thank you.

**Comment by eliben** [comment]
You should be inside a Go module.

Work through this official Go tutorial: https://go.dev/doc/tutorial/create-module

**Comment by Masked-Code** [comment]
Ahh, thank you @eliben 🫡
