### ISSUE TITLE
Mismatch between explanation and example code

### ISSUE THREAD

**Issue by wondersavant** [mmcgrana/gobyexample#565]
https://gobyexample.com/enums

![Screenshot 2024-12-24 142514](https://github.com/user-attachments/assets/077fc720-5766-4888-8ce4-7289c52cc3d7)

adjust the text to match the code.

**Comment by eliben** [comment]
Can you please clarify where you see the mismatch?

**Comment by wondersavant** [comment]
"It's not a big deal, but I just wanted to let you know.

![398402322-077fc720-5766-4888-8ce4-7289c52cc3d7](https://github.com/user-attachments/assets/8a52cf4e-efc5-4f4e-8f7c-fd246b311a7a)

**Comment by eliben** [comment]
Sorry, I still don't see a mismatch. The `stateName` map is required to implement the `String()` method, so it appears first. The mention of the stringer tool is not reflected in the actual code right now
