### ISSUE TITLE
It would be nice to have some examples about how to use FlagSets, from the flag package

### ISSUE THREAD

**Issue by c4milo** [mmcgrana/gobyexample#73]

**Comment by amitsaha** [comment]
For someone looking to implement this, or just want an example: http://stackoverflow.com/a/24510031/59634 should be of help.

**Comment by mmcgrana** [comment]
Sorry, I am not planning to add more sections to Go by Example.

I've now noted this in [CONTRIBUTING.md](https://github.com/mmcgrana/gobyexample/blob/master/CONTRIBUTING.md), since it's a very reasonable suggestion but not one I'm able to personally accommodate right now.
