### ISSUE TITLE
Use TravisCI or Drone.io for continuous integration 

### ISSUE THREAD

**Issue by mathonsunday** [mmcgrana/gobyexample#91]
So folks don't have to manually build the site from source every time they make a change.

**Comment by mmcgrana** [comment]
Good idea! I don't think I'll have time to implement this personally, but I'd accept a PR if it was reasonably  clean (gobyexample is a bit of an unusual project, so not sure exactly how gnarly such a setup would be).

**Comment by mmcgrana** [comment]
Going to close as I don't plan to pursue this myself, but still open to PRs.
