### ISSUE TITLE
Need suggestion about translation

### ISSUE THREAD

**Issue by Oire** [mmcgrana/gobyexample#92]
Hello,  
I would like to translate GoByExample into Russian. As I could see, a guy translated it into Chinese _after_ building the HTML files.  
So, what is actually a good way to translate this into another language?  
Thanks!

**Comment by mmcgrana** [comment]
Hi @Oire. I'm excited to hear you're interested in translating to Russian!

I think your best bet for translating would be to fork the project and translate the comment text in the source .go and .sh files to Russian. Then you could use the existing toolchain to rebuild the static files (and the existing server for serving them if you wanted).

You may need to make some associated tweaks  to templates and the toolchains, but I think that should basically work. For example, if you wanted to rename the examples / change the associated URLs, you'd need to change the names of the directories / folders in examples and the corresponding entries in examples.txt.

If you run into any issues with this, feel free to open an issue here or write to me directly at mmcgrana@gmail.com. Good luck!

**Comment by Oire** [comment]
@mmcgrana, thanks Mark! Actually, my main question is about how to serve this to the public after translating. Should I purchase a VPS or some shared hosting plan supporting Go or could it be done in another way?) Thanks!

**Comment by everyx** [comment]
@Oire I'm the translator of the Chinese version, I have change a little of code of `tools/generate.go` and add some translate rule so i can translate `examples.txt` and generate code to the root directory, so that i can use `gh-pages` to serve the static site on GitHub.

You can checkout the `tools/generate.go` and find out the difference.

**Comment by Oire** [comment]
Thanks @everyx, will look at it!
